[package]
name = "me"
authors = ["Albert Attard <albertattard@gmail.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.14"
clap = { version = "4.5.3", features = ["derive"] }
regex = "1.10.3"
