name: Build application

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Update Rust
        run: |
          rustup update

      - name: Build application
        run: |
          cargo build --release

      - name: Run the tests
        run: |
          cargo test
